baseurl = "https://www.jordanhutchings.com/"
title = "Jordan Hutchings"
author = "Jordan Hutchings"
canonifyurls = true
relativeURLs = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

# googleAnalytics = "UA-00000000-1"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
pagetitle = "Jordan Hutchings"
copyright = "© 2022 Jordan Hutchings"
copyrightUrl = "https://www.jordanhutchings.com"
faviconfile = "image/favicon2.png"
logofile = "image/jhutchings-avatar.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "jjhutchi"
twitter = "jjhutchi01"
linkedin = "jordan-hutchings"
email = "jordanhutch04@gmail.com"

[[menu.primary]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
    
[[menu.primary]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 3
    
[[menu.primary]]
    identifier = "CV"
    name = "CV"
    url = "/pdf/academic-cv.pdf"
    weight = 4
    
[[menu.primary]]
    identifier = "misc"
    name = "Misc"
    url = "/misc/"
    weight = 5
    
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
