---
title: Daily Mental Health Tracker
author: Jordan Hutchings
date: '2022-08-12'
slug: []
categories:
  - blog
tags:
  - R
  - Cron
  - Wellbeing
meta_img: image/image.png
description: Description for the page.
---

## Motivation

The one downside with tracking your wellbeing is that on your worst days you 
feel the least motivated to track your mental state. 

This blog post shows how I created a simple process to log my wellbeing 
each day driven by R, and using Google Sheet forms. 

### Creating a google sheet form

TBD: make a form in Google Sheets that allows you to answer how you are feeling. 

### Send daily push notifications to your phone

TBD: Set a cronR job to send the link to your phone daily from an R script. 
NOTE: you can also set up a shortcut probably in iOS. 

### Write some code to collect and analyze the results from the google sheet. 

The googlesheet form saves automatically in a data page. Simply use 
`googlesheets4` to collect this information. 


# Developer info

```{r}
# google form googlesheet link - to send to phone
url = "https://docs.google.com/forms/d/e/1FAIpQLSfRS0VR__4gjwmOJ1XbD3MA8_nUefWXuyHnWTt3bd1eO2Hw8Q/viewform?usp=sf_link"

# spreadsheet which saves the data
ss = "https://docs.google.com/spreadsheets/d/1madkBUqrB6QJV0C5xLArAV6uUE_CajMyQngPcviNokY/edit?resourcekey#gid=1309096378"


```
